### ISSUE TITLE
Markbot

### ISSUE THREAD

**Issue by heatherlyall** [heatherlyall/using-svg-icons#1]
Hi! Markbot keeps saying that theres a parse error in my code that I cannot for the life of me figure it out @hellachella
<img width="451" alt="Screen Shot 2020-10-12 at 11 53 50 AM" src="https://user-images.githubusercontent.com/55193092/95794381-bded6e00-0cb5-11eb-976b-0e5f30b165bd.png">
<img width="580" alt="Screen Shot 2020-10-12 at 11 56 00 AM" src="https://user-images.githubusercontent.com/55193092/95794382-bf1e9b00-0cb5-11eb-9f13-f392dc732251.png">

**Comment by MacKenzieRose** [comment]
Hey~

I'm not able to recreate the error you're getting; did you push all of your code to Github? Or were you able to resolve it?

**Comment by MacKenzieRose** [comment]
Hey~

Things like the `moz-text-size-adjust: 100%` need to sit inside your `html` selector in your CSS; the code that I downloaded doesn't do that, but your screenshot above does.

I'm guessing not all of your code has been pushed to Github, so can you push your most recent changes, and I'll help you troubleshoot your most up-to-date code? (Unless you solved this error already!) 😄
